imports:
    - { resource: parameters_default.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1.0.0
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:     session.handler.pdo
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        site_name: %site_name%
        site_url: %site_url%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

parameters:
    session.handler.pdo.options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time
    redwood.upload.public_directory: "%kernel.root_dir%/../web/files"
    redwood.upload.public_url_path: "/files"

services:
    session.handler.pdo.connection:
        class: PDO
        calls:
            - [setAttribute, [3, 2]]

        arguments:
            dsn:      "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            user:     %database_user%
            password: %database_password%

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@session.handler.pdo.connection, %session.handler.pdo.options%]

    redwood.twig.web_extension:
        class: Redwood\WebBundle\Twig\Extension\WebExtension
        arguments:    [@service_container]
        tags:
            - { name: twig.extension }

    redwood.twig.html_extension:
        class: Redwood\WebBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: twig.extension }

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    # spool:     { type: memory }