#不要修改此配置
parameters:
    site_name: Redwood
    site_url: www.111dev.com
    weibo_key: testdata
    qq_key: testdata

    route_white_list: ['/uploader/upload_callback', '/uploader/process_callback', '/coin/pay/return/alipay','/coin/pay/notify/alipay','/login', '/login_check']