#不要修改此配置
parameters:
    site_name: Redwood
    site_url: www.111dev.com
    is_mail_server_open: false

    third_login_password: 12345678
    weibo_key: testdata
    qq_key: testdata
    gitlab_key: c8bf2838398022e9163d083399cf083f1053978b3ff279e45e1f3513e1bdd7d2
    gitlab_secret: cb15fedd128ef9272365f5b79be3e122fdd0cec95be82ea3061bb63976624e41
    route_white_list: ['/uploader/upload_callback', '/uploader/process_callback', '/coin/pay/return/alipay','/coin/pay/notify/alipay','/login', '/login_check']
