admin_square:
    pattern:  /square
    defaults: { _controller: RedwoodAdminBundle:Default:index }

admin_user:
    pattern: /user
    defaults: { _controller: RedwoodAdminBundle:User:index }

admin_user_show:
    pattern: /user/{id}
    defaults: { _controller: RedwoodAdminBundle:User:show }

# admin_user_edit:
#     pattern: /user/{id}/edit
#     defaults: { _controller: RedwoodAdminBundle:User:edit }

admin_user_roles:
    pattern:  /user/{id}/roles
    defaults: { _controller: RedwoodAdminBundle:User:roles }

admin_user_lock:
    pattern:  /user/{id}/lock
    defaults: { _controller: RedwoodAdminBundle:User:lock }
    methods:  [POST]

admin_user_unlock:
    pattern:  /user/{id}/unlock
    defaults: { _controller: RedwoodAdminBundle:User:unlock }
    methods:  [POST]

admin_user_send_passwordreset_email:
    pattern:  /user/{id}/send_passwordreset_email
    defaults: { _controller: RedwoodAdminBundle:User:sendPasswordResetEmail }
    methods:  [POST]

admin_user_send_emailverify_email:
    pattern:  /user/{id}/send_emailverify_email
    defaults: { _controller: RedwoodAdminBundle:User:sendEmailVerifyEmail }
    methods:  [POST]


admin_jswidget:
    pattern:  /widget/{filter}/index
    defaults: { _controller: RedwoodAdminBundle:Jswidget:index, filter:'normal' }

admin_tag:
    pattern:  /tag
    defaults: { _controller: RedwoodAdminBundle:Tag:index }

admin_tag_create:
    pattern:  /tag/create
    defaults: { _controller: RedwoodAdminBundle:Tag:create }

admin_tag_delete:
    pattern:  /tag/{id}/delete
    defaults: { _controller: RedwoodAdminBundle:Tag:delete }

admin_tag_update:
    pattern:  /tag/{id}/update
    defaults: { _controller: RedwoodAdminBundle:Tag:update }

admin_tag_checkname:
    pattern:  /tag/checkname
    defaults: { _controller: RedwoodAdminBundle:Tag:checkName}

